dist: trusty
sudo: required
language: java
jdk:
    - oraclejdk8

before_install:
    - mkdir -p $HOME/bin
    - wget https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-linux-amd64-1.2.1.tar.gz
    - tar xvzf git-lfs-linux-amd64-1.2.1.tar.gz
    - mv git-lfs-1.2.1/git-lfs $HOME/bin/git-lfs
    - export PATH=$PATH:$HOME/bin
    - git lfs install
    - git config -f .lfsconfig lfs.url http://travis:travis@pa.veyry.fr:9999
    - git lfs env
    - sudo apt-get -qq update
    - sudo apt-get install oracle-java8-installer

script:
    - git lfs pull
    - mvn clean test

notifications:
  slack:
    secure: C/LIWqciaDTiw7SDoV/LJKlU4zdiE5+8zyJfUAwXXD08ioN3ciaX9OGzMO/Jx/U6I7BLgsPWsUoOlqGL8/9ISitZprSu6ADtd1ZuqE/h376vuPlDd/VNk3xSDe6/v7OBk7WRIzrwiEARVZmjD3J165suS+s7/lYLs1Vq6T33emfISN3669lMQ8xEvxq9EkwipxmcxcS3mK5N+x84HT5oM8oft7pggHC7ZEVsgonvFgLh5/+0p5iI12deadGu4wKZzaX6dxMaQtLYP70AG9CwJh8r3YpqGHZoEoNNpHDfa753sIHejCjGKGGEyqpf7MS7wv2iePREWRYKiaVIXyw3aCjG4Xlmr1ckqUNbJj1jpjecugG0/L+c5yzj4jC2VnhkA8G7g1mNnUor8nS42ZfCeTnbGIFvHqpQQm6tTvOuPExoL6lJjT1aZ5/s0tMeXzRy/VY/Vxs1RM6quZZD4WnI/1pvQaeEwOh6h6ipJuxEawXkydAuUXYIoOhYdkURJ1X5XsLIBC4mA4mLf8YgKlYdsKD2zvj0q/KY8ZCVk8mn5HbO3GGWGEPKrOFh8ITpuZQhA8FwnQ6UrBunHPvZk8O/f58wZYQV1X0zi0LlyjVK+FJMoMICnVyPH+6ImgmauLdGr3/PxlzCdko+rdC6BhqYH9saleB9L69uLK/rdOh1eoY=
